lista_palabras = ['cuchillo',
                  'tenedor',
                  'cuchara',
                  'plato',
                  'vaso',
                  'taza',
                  'olla',
                  'sarten',
                  'sal',
                  'pimienta',
                  'azucar',
                  'harina',
                  'aceite',
                  'agua',
                  'leche',
                  'huevo',
                  'pan',
                  'carne']
